"""Domain models for vision analysis.

These lightweight data containers hold the analysis results returned by the Gemini
Vision API.  The provider aggregates per‑frame analysis into per‑scene summaries
and finally returns a :class:`VisionAnalysisResult`.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import List


@dataclass(frozen=True)
class FrameAnalysis:
    """Analysis for a single frame.

    Attributes
    ----------
    scene_index: int
        Index of the scene the frame belongs to.
    frame_index: int
        Index of the frame within the scene.
    image_path: Path
        Path to the JPEG image that was analysed.
    description: str
        Free‑form textual description generated by the LLM.
    objects: List[str]
        Detected objects.
    characters: List[str]
        Detected characters (people, avatars, etc.).
    actions: List[str]
        Detected actions performed in the frame.
    emotions: List[str]
        Detected emotions.
    """

    scene_index: int
    frame_index: int
    image_path: Path
    description: str
    objects: List[str]
    characters: List[str]
    actions: List[str]
    emotions: List[str]


@dataclass(frozen=True)
class SceneAnalysis:
    """Aggregated analysis for a scene.

    Attributes
    ----------
    scene_index: int
        Index of the scene.
    summary: str
        High‑level textual summary of the scene.
    key_objects: List[str]
        Most important objects across the scene.
    key_characters: List[str]
        Most important characters.
    key_actions: List[str]
        Most important actions.
    dominant_emotion: str
        Predominant emotion detected in the scene.
    """

    scene_index: int
    summary: str
    key_objects: List[str]
    key_characters: List[str]
    key_actions: List[str]
    dominant_emotion: str


@dataclass(frozen=True)
class VisionAnalysisResult:
    """Result container returned by the vision analyzer.

    Attributes
    ----------
    scenes: List[SceneAnalysis]
        One analysis per scene.
    processing_time: float
        Total time spent (seconds) for the whole analysis.
    """

    scenes: List[SceneAnalysis]
    processing_time: float

    @staticmethod
    def empty() -> "VisionAnalysisResult":
        return VisionAnalysisResult(scenes=[], processing_time=0.0)
