"""Review Planner Agent (Agent 2).

Designs the storytelling structure to maximize audience retention while
remaining completely faithful to the movie_memory.json.
"""

from __future__ import annotations

import json
from typing import Any, Optional, List, Dict
from src.agents.models import (
    MovieMemory,
    ReviewPlan,
    ChapterPlan,
    ClimaxStrategy,
    EndingStrategy,
)
from src.utils.logger import get_logger

_logger = get_logger("review_planner")


class ReviewPlannerAgent:
    """Logical Agent 2: Storytelling Blueprint & Retention Architect."""

    REVIEW_PLANNER_SYSTEM_PROMPT = """You are Review Planner, the second AI agent in a multi-agent movie review system.

Your responsibility is NOT to write the review.
Your responsibility is to design the storytelling structure that will maximize audience retention while remaining completely faithful to the original movie.

You will receive:
• movie_memory.json generated by Story Analyst
This file is the ONLY source of truth.
Do not infer information outside movie_memory.json.

=========================================================
GOAL
=========================================================
Create a complete narrative blueprint for a professional YouTube movie recap.
The review should feel like an experienced human storyteller.
Do NOT simply retell scenes in chronological order.
Instead, organize the story to maximize curiosity, emotional engagement and viewer retention while preserving story accuracy.

=========================================================
PLANNING PRINCIPLES
=========================================================
Your objective is NOT to summarize.
Your objective is to answer:
How should this story be told?

Determine:
• Which event should become the Hook.
• Which information should be delayed.
• Which mystery should remain unanswered until later.
• Which scenes deserve more narration.
• Which scenes should be shortened.
• Which scenes can be skipped.
• Where suspense should increase.
• Where emotional pacing should slow down.
• Where plot twists should be revealed.

Never change the movie.
Only change the order in which information is presented to the audience.

=========================================================
HOOK DESIGN
=========================================================
Create one powerful opening hook.
The hook should naturally create curiosity.
Good examples:
"What if everything you believed about this character was a lie?"
"He thought he had escaped... but one tiny mistake changed everything."
The hook must NOT spoil the ending.

=========================================================
STORY STRUCTURE
=========================================================
Divide the review into logical chapters.
For every chapter determine:
• title
• objective
• included_scenes
• skipped_scenes
• review_priority (high / medium / low)
• emotional_tone (Curiosity, Mystery, Hope, Fear, Shock, Sadness, Relief)
• suspense_level (1-10)
• transition_goal

=========================================================
CLIMAX STRATEGY
=========================================================
Determine:
• Which event should become the emotional peak.
• Which information should be hidden until the climax.
• Which earlier scenes should be referenced again.

=========================================================
ENDING STRATEGY
=========================================================
Determine:
• How to conclude the story naturally.
• Final emotional tone.
• Optional discussion question for viewers.
The ending should encourage reflection rather than simply ending the plot.

=========================================================
STRICT RULES
=========================================================
- Never invent scenes.
- Never invent dialogue.
- Never invent motivations.
- Never invent twists.
- Never contradict movie_memory.json.
- Do not write the review.
- Do not write narration.
- Do not explain your reasoning.

Return ONLY valid JSON in the following format:
{
  "hook": "Powerful curiosity hook without spoilers",
  "intro": "Brief engaging introduction",
  "chapters": [
    {
      "chapter_index": 1,
      "title": "Chapter Title",
      "objective": "Storytelling objective of this chapter",
      "included_scenes": [1, 2, 3],
      "skipped_scenes": [],
      "review_priority": "high",
      "emotional_tone": "Curiosity",
      "suspense_level": 7,
      "transition_goal": "Bridge to the escalating conflict",
      "key_events": ["Key event 1", "Key event 2"]
    }
  ],
  "climax_strategy": {
    "emotional_peak_event": "The central turning point or confrontation",
    "hidden_until_climax": ["Secret or mystery revealed only at climax"],
    "earlier_scenes_to_reference": ["Scene 2 setup clue"],
    "climax_focus": "The peak showdown or revelation"
  },
  "ending_strategy": {
    "conclusion": "How the story concludes naturally",
    "final_emotional_tone": "Relief",
    "discussion_question": "Provocative question for viewers to comment on",
    "ending_text": "Closing reflection"
  },
  "target_duration_sec": 180,
  "style": "documentary"
}"""

    def __init__(self, browser_mgr: Optional[Any] = None) -> None:
        self._browser_mgr = browser_mgr

    def build_planning_prompt(self, memory: MovieMemory) -> str:
        """Construct the prompt containing movie_memory.json for LLM generation."""
        memory_json = json.dumps(memory.to_dict(), ensure_ascii=False, indent=2)
        return (
            f"{self.REVIEW_PLANNER_SYSTEM_PROMPT}\n\n"
            f"================ INPUT: movie_memory.json ================\n"
            f"{memory_json}\n"
            f"==========================================================\n"
            f"Generate the storytelling blueprint and return ONLY the valid JSON object."
        )

    def plan(
        self,
        memory: MovieMemory,
        timeline: Any = None,
        style: str = "documentary",
        target_duration: int = 180,
    ) -> ReviewPlan:
        """Create structured ReviewPlan blueprint."""
        _logger.info("Review Planner Agent designing storytelling blueprint (style={})...", style)

        main_char = memory.characters[0].name if memory.characters else "Nhân vật chính"

        # 1. Hook Design
        if memory.curiosity_moments:
            q = memory.curiosity_moments[0].question
            hook = f"{q} Một quyết định bất ngờ đã đảo lộn toàn bộ tình thế của {main_char}."
        else:
            hook = f"Bạn sẽ phản ứng ra sao nếu một sai lầm nhỏ bất ngờ biến cuộc sống bình thường thành cuộc chiến sinh tử nghẹt thở?"

        # 2. Intro
        intro = f"Chào mừng các bạn đến với video review phân tích tác phẩm điện ảnh kịch tính hôm nay. Hãy cùng khám phá từng nút thắt và bí mật đằng sau câu chuyện này."

        # 3. Chapters with included/skipped scenes and retention strategy
        total_scenes = len(memory.scenes_analysis)
        all_indices = [s.scene_index for s in memory.scenes_analysis] if memory.scenes_analysis else [1, 2, 3]

        if total_scenes >= 3:
            s1 = all_indices[: max(1, total_scenes // 3)]
            s2 = all_indices[max(1, total_scenes // 3): max(2, (2 * total_scenes) // 3)]
            s3 = all_indices[max(2, (2 * total_scenes) // 3):]
        else:
            s1, s2, s3 = [1], [2], [3]

        # Prioritize scenes with high importance scores (> 6)
        skipped = [s.scene_index for s in memory.scenes_analysis if s.importance_score < 4]

        plot_points = memory.key_plot_points or [s.what_happens for s in memory.scenes_analysis]
        ch1_events = plot_points[: max(1, len(plot_points) // 3)]
        ch2_events = plot_points[max(1, len(plot_points) // 3): max(2, (2 * len(plot_points)) // 3)]
        ch3_events = plot_points[max(2, (2 * len(plot_points)) // 3):]

        chapters = [
            ChapterPlan(
                chapter_index=1,
                title="Khởi Đầu & Nút Thắt Bí Ẩn",
                objective="Thiết lập bối cảnh, nhân vật chính và sự kiện châm ngòi tạo sự tò mò",
                narrative_focus="Giới thiệu xuất phát điểm và kích hoạt câu hỏi mở cho người xem",
                included_scenes=[idx for idx in s1 if idx not in skipped],
                skipped_scenes=[idx for idx in s1 if idx in skipped],
                review_priority="high",
                emotional_tone="Curiosity",
                suspense_level=6,
                transition_goal="Đẩy nhanh nhịp độ khi mâu thuẫn bắt đầu xuất hiện",
                key_events=ch1_events,
            ),
            ChapterPlan(
                chapter_index=2,
                title="Biến Cố Dồn Dập & Thử Thách",
                objective="Khai thác các xung đột liên tiếp, gia tăng căng thẳng và bí ẩn",
                narrative_focus="Mở rộng thử thách, che giấu các thông tin then chốt cho hồi kết",
                included_scenes=[idx for idx in s2 if idx not in skipped],
                skipped_scenes=[idx for idx in s2 if idx in skipped],
                review_priority="high",
                emotional_tone="Fear",
                suspense_level=8,
                transition_goal="Dẫn dắt cảm xúc người xem chạm ngưỡng bùng nổ trước cao trào",
                key_events=ch2_events,
            ),
            ChapterPlan(
                chapter_index=3,
                title="Cao Trào Bùng Nổ & Sự Thật Phơi Bày",
                objective="Giải mã mọi nút thắt, giải quyết xung đột đỉnh điểm và đem lại bài học",
                narrative_focus="Đối đầu quyết định và hé lộ lời giải cho các manh mối cài cắm",
                included_scenes=[idx for idx in s3 if idx not in skipped],
                skipped_scenes=[idx for idx in s3 if idx in skipped],
                review_priority="high",
                emotional_tone="Shock",
                suspense_level=10,
                transition_goal="Chuyển nhịp từ căng thẳng sang lắng đọng và suy ngẫm",
                key_events=ch3_events,
            ),
        ]

        # 4. Climax Strategy
        climax_strategy = ClimaxStrategy(
            emotional_peak_event=memory.storyline.climax or f"Phân cảnh đối đầu quyết định của {main_char}",
            hidden_until_climax=[f.clue for f in memory.foreshadowing] if memory.foreshadowing else ["Sự thật đằng sau động cơ của nhân vật"],
            earlier_scenes_to_reference=[f"Cảnh {f.setup_scene}" for f in memory.foreshadowing if f.setup_scene] if memory.foreshadowing else ["Cảnh mở đầu"],
            climax_focus="Đỉnh điểm xung đột và khúc ngoặt giải phóng mọi áp lực của câu chuyện",
        )

        # 5. Ending Strategy
        ending_strategy = EndingStrategy(
            conclusion=memory.storyline.ending or "Cái kết trọn vẹn mang lại sự thấu hiểu sâu sắc cho người xem.",
            final_emotional_tone="Relief",
            discussion_question=f"Nếu ở vị trí của {main_char}, bạn sẽ lựa chọn hành động ra sao? Hãy chia sẻ suy nghĩ dưới phần bình luận nhé!",
            ending_text="Cảm ơn các bạn đã theo dõi. Đừng quên bấm Like và Đăng ký kênh để đón xem những câu chuyện điện ảnh hấp dẫn tiếp theo!",
        )

        plan = ReviewPlan(
            hook=hook,
            intro=intro,
            chapters=chapters,
            climax_strategy=climax_strategy,
            ending_strategy=ending_strategy,
            climax_focus=climax_strategy.climax_focus,
            ending=ending_strategy.ending_text,
            target_duration_sec=target_duration,
            style=style,
        )

        _logger.info("Review Planner finished: generated blueprint with {} chapters", len(chapters))
        return plan

